version: "3"

services:
  app:
    build: .
    container_name: simulator
    volumes:
      - .:/go/src/ # compartilha mesma pasta no computador
    extra_hosts:
      - "host.docker.internal:172.17.0.1"